// Package lines removes whole lines that match a pattern: AI attribution
// footers, "as an AI language model" disclaimers, generator comments.
//
// This is a third, coarser layer than the rest of the tool. Layer A edits
// individual runes and can always justify each one; this deletes entire lines
// on a regular-expression match, which is destructive and cannot tell a
// disclaimer from a sentence that merely mentions one. It is opt-in for that
// reason, and every caller is expected to offer a dry run.
package lines

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// DefaultPatterns matches common AI attribution lines, disclaimers and
// vendor/model names.
//
// These are deliberately broad, and several are broad enough to be dangerous:
// `llm`, `claude` and `gemini` match as substrings anywhere in a line, so a
// paragraph discussing an LLM, a variable named `claudeClient`, or a citation
// is removed just as readily as a generated footer. That is the intended
// behavior for scrubbing attribution out of your own output, and a very poor
// default for a source tree. Preview with a dry run before writing.
func DefaultPatterns() []string {
	return []string{
		// Generic attribution
		`(?i)generated by ai`,
		`(?i)ai-generated`,
		`(?i)created by (chatgpt|copilot|claude|bard|gemini|llama)`,
		`(?i)this (code|text|response) was (generated|written|produced) by`,
		`(?i)generated with`,
		`(?i)powered by ai`,
		`(?i)as an ai (language model|assistant)`,
		`(?i)i am an ai`,
		`(?i)ai assistant`,
		`(?i)large language model`,
		`(?i)llm`,
		`(?i)openai`,
		`(?i)anthropic`,
		`(?i)google ai`,
		`(?i)meta ai`,
		`(?i)copilot`,
		`(?i)chatgpt`,
		`(?i)claude`,
		`(?i)bard`,
		`(?i)gemini`,
		`(?i)llama`,

		// Common footers / headers
		`(?i)^# ai-generated`,
		`(?i)^// generated by`,
		`(?i)^/\* generated by`,
		`(?i)<!-- generated by`,
		`(?i)\*\*\* generated by`,

		// Disclaimers
		`(?i)this content may contain errors`,
		`(?i)please verify`,
		`(?i)not professional advice`,
		`(?i)for informational purposes only`,

		// Model specific
		`(?i)gpt-3`,
		`(?i)gpt-4`,
		`(?i)claude-`,
		`(?i)gemini-`,
		`(?i)llama-`,
		`(?i)codex`,
		`(?i)codellama`,
	}
}

// Compile turns pattern strings into regexps, naming the offender on failure.
func Compile(patterns []string) ([]*regexp.Regexp, error) {
	out := make([]*regexp.Regexp, 0, len(patterns))
	for _, p := range patterns {
		re, err := regexp.Compile(p)
		if err != nil {
			return nil, fmt.Errorf("invalid pattern %q: %w", p, err)
		}
		out = append(out, re)
	}
	return out, nil
}

// LoadPatternFile reads one pattern per line, skipping blanks and # comments.
func LoadPatternFile(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var patterns []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		patterns = append(patterns, line)
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return patterns, nil
}

// Filter decides which lines survive.
type Filter struct {
	// Patterns removes any line matching one of these.
	Patterns []*regexp.Regexp
	// StripComments removes every line that looks like a single-line comment,
	// regardless of content. This breaks code that relies on comment
	// directives (build tags, linter pragmas, shebangs) and is a last resort.
	StripComments bool
}

// Active reports whether the filter would do anything at all.
func (f Filter) Active() bool {
	return len(f.Patterns) > 0 || f.StripComments
}

// Match records one removed line, for reporting and dry runs.
type Match struct {
	// Line is the 1-based line number in the input.
	Line int `json:"line"`
	// Text is the line's content, without its terminator.
	Text string `json:"text"`
	// Pattern is the regexp that matched, or "comment" for a comment strip.
	Pattern string `json:"pattern"`
}

// Result summarizes what a filter pass removed.
type Result struct {
	Removed int     `json:"removed"`
	Matches []Match `json:"matches,omitempty"`
}

// maxRecordedMatches caps the detail kept for reporting. A pattern like
// `(?i)llm` against a large corpus can match nearly every line, and the caller
// only ever shows a sample; Removed stays exact.
const maxRecordedMatches = 200

// Apply removes matching lines from text and reports what went.
//
// Line terminators are preserved exactly as they were found, so a CRLF file
// stays CRLF and a file with no trailing newline does not gain one.
func (f Filter) Apply(text string) (string, Result) {
	var res Result
	if !f.Active() || text == "" {
		return text, res
	}

	var b strings.Builder
	b.Grow(len(text))

	for i, ln := range splitLines(text) {
		if pattern, drop := f.reject(ln.content); drop {
			res.Removed++
			if len(res.Matches) < maxRecordedMatches {
				res.Matches = append(res.Matches, Match{
					Line:    i + 1,
					Text:    ln.content,
					Pattern: pattern,
				})
			}
			continue
		}
		b.WriteString(ln.content)
		b.WriteString(ln.terminator)
	}
	return b.String(), res
}

// reject reports whether a line should go, and what caught it.
func (f Filter) reject(content string) (string, bool) {
	if f.StripComments && IsCommentLine(content) {
		return "comment", true
	}
	for _, re := range f.Patterns {
		if re.MatchString(content) {
			return re.String(), true
		}
	}
	return "", false
}

// line is one input line and the terminator that followed it.
type line struct {
	content    string
	terminator string
}

// splitLines splits text into lines, keeping each terminator separate so a
// rewrite can reproduce the original line endings byte for byte. A final
// fragment with no terminator is returned with an empty one; a trailing
// newline does not produce a spurious empty last line.
func splitLines(text string) []line {
	var out []line
	for len(text) > 0 {
		idx := strings.IndexByte(text, '\n')
		if idx < 0 {
			out = append(out, line{content: text})
			break
		}
		content := text[:idx]
		term := "\n"
		if strings.HasSuffix(content, "\r") {
			content = content[:len(content)-1]
			term = "\r\n"
		}
		out = append(out, line{content: content, terminator: term})
		text = text[idx+1:]
	}
	return out
}

// commentPrefixes are single-line comment markers across common languages.
var commentPrefixes = []string{"//", "#", "--", "/*", "*/", "<!--", "-->", "%%", "!"}

// IsCommentLine reports whether a line looks like a single-line comment or the
// start of a docstring. Blank lines are not comments and are always kept.
func IsCommentLine(s string) bool {
	trimmed := strings.TrimSpace(s)
	if trimmed == "" {
		return false
	}
	if strings.HasPrefix(trimmed, `"""`) || strings.HasPrefix(trimmed, `'''`) {
		return true
	}
	for _, p := range commentPrefixes {
		if strings.HasPrefix(trimmed, p) {
			return true
		}
	}
	return false
}
