package lines

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func mustFilter(t *testing.T, patterns ...string) Filter {
	t.Helper()
	compiled, err := Compile(patterns)
	if err != nil {
		t.Fatal(err)
	}
	return Filter{Patterns: compiled}
}

func defaultFilter(t *testing.T) Filter {
	t.Helper()
	return mustFilter(t, DefaultPatterns()...)
}

func TestDefaultPatternsCompile(t *testing.T) {
	if _, err := Compile(DefaultPatterns()); err != nil {
		t.Fatalf("built-in patterns do not compile: %v", err)
	}
}

func TestRemovesAttributionLines(t *testing.T) {
	in := strings.Join([]string{
		"# My Document",
		"",
		"Some real content here.",
		"Generated by AI",
		"More real content.",
		"As an AI language model, I cannot do that.",
		"The end.",
	}, "\n")

	got, res := defaultFilter(t).Apply(in)
	if res.Removed != 2 {
		t.Errorf("Removed = %d, want 2: %+v", res.Removed, res.Matches)
	}
	for _, gone := range []string{"Generated by AI", "As an AI language model"} {
		if strings.Contains(got, gone) {
			t.Errorf("%q survived:\n%s", gone, got)
		}
	}
	for _, kept := range []string{"# My Document", "Some real content here.", "The end."} {
		if !strings.Contains(got, kept) {
			t.Errorf("lost %q:\n%s", kept, got)
		}
	}
}

func TestMatchesReportLineAndPattern(t *testing.T) {
	in := "one\ntwo\nGenerated by AI\nfour"
	_, res := defaultFilter(t).Apply(in)
	if len(res.Matches) != 1 {
		t.Fatalf("Matches = %+v, want 1", res.Matches)
	}
	m := res.Matches[0]
	if m.Line != 3 {
		t.Errorf("Line = %d, want 3", m.Line)
	}
	if m.Text != "Generated by AI" {
		t.Errorf("Text = %q", m.Text)
	}
	if !strings.Contains(m.Pattern, "generated by ai") {
		t.Errorf("Pattern = %q, want the matching regexp", m.Pattern)
	}
}

func TestPreservesCRLF(t *testing.T) {
	in := "keep\r\nGenerated by AI\r\nalso keep\r\n"
	got, res := defaultFilter(t).Apply(in)
	if res.Removed != 1 {
		t.Fatalf("Removed = %d, want 1", res.Removed)
	}
	if got != "keep\r\nalso keep\r\n" {
		t.Errorf("got %q, want CRLF preserved", got)
	}
}

func TestPreservesMissingTrailingNewline(t *testing.T) {
	// A file with no final newline must not gain one, and one with a final
	// newline must not lose it.
	for _, tc := range []struct{ in, want string }{
		{"a\nGenerated by AI\nb", "a\nb"},
		{"a\nGenerated by AI\nb\n", "a\nb\n"},
		{"Generated by AI\nb", "b"},
		{"a\nGenerated by AI", "a\n"},
	} {
		got, _ := defaultFilter(t).Apply(tc.in)
		if got != tc.want {
			t.Errorf("Apply(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestInactiveFilterIsIdentity(t *testing.T) {
	in := "Generated by AI\nanything at all\n"
	var f Filter
	if f.Active() {
		t.Error("zero-value Filter reports itself active")
	}
	got, res := f.Apply(in)
	if got != in || res.Removed != 0 {
		t.Errorf("inactive filter changed the text: %q", got)
	}
}

func TestCustomPatternsOnly(t *testing.T) {
	f := mustFilter(t, `(?i)^TODO:`)
	in := "keep\nTODO: fix this\nGenerated by AI\n"
	got, res := f.Apply(in)
	if res.Removed != 1 {
		t.Errorf("Removed = %d, want 1", res.Removed)
	}
	// The built-in patterns are not in play, so the attribution line stays.
	if !strings.Contains(got, "Generated by AI") {
		t.Errorf("custom pattern set should not include the built-ins:\n%s", got)
	}
}

func TestStripComments(t *testing.T) {
	in := strings.Join([]string{
		"package main",
		"// a comment",
		"# another",
		"code := 1",
		"",
		"   -- sql comment",
		`"""docstring`,
	}, "\n")

	f := Filter{StripComments: true}
	got, res := f.Apply(in)
	if res.Removed != 4 {
		t.Errorf("Removed = %d, want 4: %+v", res.Removed, res.Matches)
	}
	for _, kept := range []string{"package main", "code := 1"} {
		if !strings.Contains(got, kept) {
			t.Errorf("lost %q:\n%s", kept, got)
		}
	}
	// Blank lines are not comments.
	if !strings.Contains(got, "\n\n") {
		t.Errorf("blank line was removed:\n%q", got)
	}
	if res.Matches[0].Pattern != "comment" {
		t.Errorf("Pattern = %q, want %q", res.Matches[0].Pattern, "comment")
	}
}

func TestIsCommentLine(t *testing.T) {
	comments := []string{"// x", "  # x", "-- x", "/* x", "*/", "<!-- x", "--> x", "%% x", "! x", `"""x`, "'''x"}
	for _, s := range comments {
		if !IsCommentLine(s) {
			t.Errorf("IsCommentLine(%q) = false", s)
		}
	}
	for _, s := range []string{"", "   ", "code := 1", "a // trailing comment"} {
		if IsCommentLine(s) {
			t.Errorf("IsCommentLine(%q) = true", s)
		}
	}
}

func TestCompileReportsBadPattern(t *testing.T) {
	_, err := Compile([]string{`valid`, `(unclosed`})
	if err == nil || !strings.Contains(err.Error(), "(unclosed") {
		t.Errorf("err = %v, want the offending pattern named", err)
	}
}

func TestLoadPatternFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "patterns.txt")
	content := "# a comment\n\n(?i)^draft\n  (?i)internal only  \n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	got, err := LoadPatternFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{`(?i)^draft`, `(?i)internal only`}
	if len(got) != len(want) {
		t.Fatalf("got %d patterns %v, want %d", len(got), got, len(want))
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("pattern %d = %q, want %q", i, got[i], want[i])
		}
	}
}

func TestLoadPatternFileMissing(t *testing.T) {
	if _, err := LoadPatternFile(filepath.Join(t.TempDir(), "nope.txt")); err == nil {
		t.Error("expected an error for a missing pattern file")
	}
}

func TestMatchRecordingIsCapped(t *testing.T) {
	// Removed stays exact even when the recorded detail is truncated.
	var b strings.Builder
	const n = maxRecordedMatches + 50
	for range n {
		b.WriteString("Generated by AI\n")
	}
	_, res := defaultFilter(t).Apply(b.String())
	if res.Removed != n {
		t.Errorf("Removed = %d, want %d", res.Removed, n)
	}
	if len(res.Matches) != maxRecordedMatches {
		t.Errorf("Matches = %d, want it capped at %d", len(res.Matches), maxRecordedMatches)
	}
}

func TestDefaultPatternsAreBroad(t *testing.T) {
	// Pins the documented hazard: the built-in set matches substrings, so
	// ordinary prose and code that merely mention a vendor are removed. If
	// this ever stops being true the README needs updating too.
	f := defaultFilter(t)
	for _, in := range []string{
		"we chose an llm for this task",
		"claudeClient := NewClient()",
		"See the Gemini paper for details.",
		"Please verify the output before shipping.",
	} {
		if _, res := f.Apply(in); res.Removed != 1 {
			t.Errorf("expected %q to be removed by the broad built-ins", in)
		}
	}
}
